WebApps/Controllers/App04/CommentsController.cs
namespace WebApps.Controllers.App04
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;
    using WebApps.Models.App04;
    using WebApps.Services.Comments;
    using WebApps.Services.Posts;

    using static Models.ModelConstants.Post;

    [Authorize]
    public class CommentsController : Controller
    {
        /// <summary>
        /// Injected post service
        /// </summary>
        private IPostService _postService;
        /// <summary>
        /// Injected comment service
        /// </summary>
        private ICommentService _commentService;
        /// <summary>
        /// Injected user manager
        /// </summary>
        private UserManager<User> _userManager;

        public CommentsController(
            IPostService postService,
            ICommentService commentService,
            UserManager<User> userManager)
        {
            this._postService = postService;
            this._commentService = commentService;
            this._userManager = userManager;
        }

        //GET: Comments/ListCommentsByPostId
        public IActionResult ListCommentsByPostId(int postId)
        {
            if (this._postService.IsPostExist(postId))
            {
                var comments = this._commentService
                    .GetCommentsByPostId(postId);

                return View(comments);
            }
            return NotFound(postId);
        }

        // GET: Comments/Create
        public IActionResult Create(int postId)
        {
            if (this._postService.IsPostExist(postId))
            {
                return View(new Comment
                {
                    PostId = postId
                });
            }
            return NotFound(postId);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Comment comment)
        {
            Validate(comment);

            if (ModelState.IsValid)
            {
                comment.AuthorId = this._userManager.GetUserId(User);
                comment.CreatedOn = DateTime.Now;

                await this._commentService.AddComment(comment);

                return RedirectToAction("Index", "HomeSocialNetwork");
            }
            return View(comment);
        }

        /// <summary>
        /// validate whether the comment valid
        /// </summary>
        /// <param name="comment">the comment to be validated</param>
        private void Validate(Comment comment)
        {
            if (comment.Content is null || comment.Content.Length < MIN_CONTENT_LENGTH || comment.Content.Length > MAX_CONTENT_LENGTH)
            {
                this.ModelState.AddModelError(nameof(Comment.Content), $"Content required and cannot be less than {MIN_CONTENT_LENGTH} or more than {MAX_CONTENT_LENGTH} symbols long.");
            }
        }
    }
}

WebApps/Controllers/App04/HomeSocialNetworkController.cs
namespace WebApps.Controllers.App04
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Linq;
    using WebApps.Services.Posts;

    /// <summary>
    /// The name of this controller is chosen in order to 
    /// be referenced easier and not to affect the main HomeController
    /// </summary>
    public class HomeSocialNetworkController : Controller
    {
        private IPostService _postService;

        public HomeSocialNetworkController(IPostService postService)
            => this._postService = postService;

        public IActionResult Index(string dateFilter = null)
        {
            if (dateFilter is not null)
            {
                var date = DateTime.Parse(dateFilter).ToString("dd/MM/yyyy");

                TempData["dateFilter"] = $"Posts published on {date}";

                return View(this._postService.GetPosts()
                    .Where(c =>c.CreatedOn.ToString("dd/MM/yyyy") == date)
                    .OrderByDescending(c =>c.CreatedOn)
                    .ToList());
            }
            return View(this._postService.GetPosts()
                .OrderByDescending(c =>c.CreatedOn)
                .ToList());
        }
    }
}

WebApps/Controllers/App04/PostsController.cs
namespace WebApps.Controllers.App04
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using WebApps.Models.App04;
    using WebApps.Services.Posts;

    using static Models.ModelConstants.Post;

    [Authorize]
    public class PostsController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IPostService _postService;
        private readonly UserManager<User> _userManager;

        public PostsController(
            IWebHostEnvironment env,
            IPostService postService,
            UserManager<User> userManager)
        {
            this._env = env;
            this._postService = postService;
            this._userManager = userManager;
        }

        // GET: Posts
        public IActionResult Index()
        {
            var currentUserId = this._userManager
                .GetUserId(User);

            return View(this._postService.GetPostsByAuthorId(currentUserId));
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post)
        {
            Validate(post);

            if (ModelState.IsValid)
            {
                var currentUserId = this._userManager.GetUserId(User);

                post.AuthorId = currentUserId;
                post.PhotoName = UploadPhoto(post.Photo, currentUserId);
                post.CreatedOn = DateTime.Now;

                await this._postService.AddPost(post);

                return RedirectToAction("Index", "HomeSocialNetwork");
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await this._postService
                .GetPostById((int)id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post post)
        {
            Validate(post);

            if (ModelState.IsValid)
            {
                try
                {
                    await this._postService.EditPost(post);
                }
                catch (Exception)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await this._postService
                .GetPostById((int)id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this._postService.DeletePost(id);

            return RedirectToAction("Index", "Profiles");
        }

        /// <summary>
        /// Increase the likes of a given post
        /// when it is not the current user.
        /// It returns true if new like is added to a post,
        /// return false if it is unliked
        /// </summary>
        [HttpPost]
        public async Task<JsonResult> IncreaseLikes([FromBody] UserLikePost userLikePost)
        {
            //If there is no id of the user who like the post, it will be set the current user`s id
            if (userLikePost.UserId is null)
            {
                userLikePost.UserId = this._userManager.GetUserId(User);
            }

            if (IsUserExist(userLikePost.UserId) && this._postService.IsPostExist(userLikePost.PostId))
            {
                var post = await this._postService
                    .GetPostById(userLikePost.PostId);

                if (await IsPostLikedAsync(userLikePost.PostId, userLikePost.UserId))
                {
                    //like to be removed 
                    var like = post.UsersLikes.FirstOrDefault(l => l.UserId == userLikePost.UserId && l.PostId == userLikePost.PostId);

                    post.UsersLikes.Remove(like);

                    await this._postService.EditPost(post);

                    return new JsonResult(false);
                }
                else
                {
                    // Add new user like post as set post id and user id
                    post.UsersLikes.Add(new UserLikePost
                    {
                        PostId = userLikePost.PostId,
                        UserId = userLikePost.UserId
                    });
                    await this._postService.EditPost(post);

                    return new JsonResult(true);
                }
            }
            else
            {
                throw new ArgumentException($"Invalid data.");
            }
        }

        private async Task<bool> IsPostLikedAsync(int postId, string userId)
        {
            var postLikes = await this._postService.GetPostById(postId);
            if (postLikes.UsersLikes.Any(l =>l.UserId == userId && l.PostId == postId))
            {
                //post is already liked by this user
                return true;
            }
            return false;
        }

        /// <summary>
        /// Save uploaded image in img folder of wwwroot
        /// </summary>
        /// <param name="uploadedPhoto">Photo to be uploaded</param>
        private string UploadPhoto(IFormFile uploadedPhoto, string authorId)
        {
            string uniqueFileName = null;

            if (uploadedPhoto != null)
            {
                string uploadsFolder = Path.Combine(this._env.WebRootPath, "img");

                uniqueFileName = $"{authorId}_{uploadedPhoto.FileName}";

                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using var fileStream = new FileStream(filePath, FileMode.Create);

                uploadedPhoto.CopyTo(fileStream);
            }
            return uniqueFileName;
        }

        /// <summary>
        /// validate whether the post valid
        /// </summary>
        /// <param name="post">the post to be validated</param>
        private void Validate(Post post)
        {
            if (post.Content is null || post.Content.Length < MIN_CONTENT_LENGTH || post.Content.Length > MAX_CONTENT_LENGTH)
            {
                this.ModelState.AddModelError(nameof(Post.Content), $"Content required and cannot be less than {MIN_CONTENT_LENGTH} or more than {MAX_CONTENT_LENGTH} symbols long.");
            }
        }

        private bool IsUserExist(string userId)
            => this._userManager.Users.Any(i => i.Id == userId);
    }
}

WebApps/Views/HomeSocialNetwork/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApps.Models.App04

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@model ICollection<Post>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_SocialNetworkLayout.cshtml";

    var currentUserId = UserManager.GetUserId(User);
}

<link rel="stylesheet" href="~/css/profile-styles.css" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

@if (!SignInManager.IsSignedIn(User))
{
    <div class="jumbotron">
        <h1 class="display-4">Social Network</h1>
        <p class="lead">This application is the first version of a system that will allow users to post messages and photos that other users can view and like. (Any similarities to Facebook is purely coincidental!).</p>
        <hr class="my-4">

        <p class="lead">
            Any user of this social network should has account for use all features.
            <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-primary">Register</a>
            <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-primary">Login</a>
        </p>
    </div>
}
else
{
    <div class="container">
        @*Filter form*@
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form asp-controller="HomeSocialNetwork" asp-action="Index" method="get">
                    <p>
                        Date: <input type="date" name="dateFilter" />
                        <input type="submit" value="Filter" />
                    </p>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
        @if (TempData["dateFilter"] is not null)
        {
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <p>@TempData["dateFilter"]</p>
                </div>
                <div class="col-md-3"></div>
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <div id="content" class="content content-full-width">
                    <div class="profile-content">
                        <!-- begin tab-content -->
                        <div class="tab-content p-0">
                            <!-- begin #profile-post tab -->
                            <div class="tab-pane fade active show" id="profile-post">
                                <ul class="timeline">
                                    @foreach (var post in Model.OrderByDescending(c => c.CreatedOn))
                                    {
                                        <li>
                                            <!-- begin timeline-time -->
                                            <div class="timeline-time">
                                                <span class="date">@post.CreatedOn.Date.ToString("dd/MM/yyyy")</span>
                                                <span class="time">@post.CreatedOn.ToString("HH:mm")</span>
                                            </div>
                                            <!-- end timeline-time -->
                                            <!-- begin timeline-icon -->
                                            <div class="timeline-icon">
                                                <a href="javascript:;">&nbsp;</a>
                                            </div>
                                            <!-- end timeline-icon -->
                                            <!-- begin timeline-body -->
                                            <div class="timeline-body">
                                                <div class="timeline-header">
                                                    <span class="username"><a href="javascript:;">@post.Author.FullName</a> <small></small></span>
                                                </div>
                                                <div class="timeline-content">
                                                    <p>@post.Content</p>
                                                    @if (post.PhotoName is not null)
                                                    {
                                                        <img src="~/img/@post.PhotoName" />
                                                    }
                                                </div>
                                                <div class="timeline-footer">
                                                    <a id="like-btn" onclick="increaseLikes('@post.PostId', '@currentUserId')" class="btn btn-primary m-r-15 text-inverse-lighter">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                                                            <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z" />
                                                        </svg>Like
                                                    </a>
                                                    <span id="users-likes-@post.PostId" class="badge badge-light">
                                                        @if (post.UsersLikes.Count > 0)
                                                        {
                                                            @post.UsersLikes.Count();
                                                        }
                                                        else
                                                        {
                                                            @: 0
                                                        }
                                                    </span>
                                                    <a asp-controller="Comments" asp-action="Create" asp-route-postId="@post.PostId" class="btn btn-success m-r-15 text-inverse-lighter">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
                                                            <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                                            <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z" />
                                                        </svg> Comment
                                                    </a>
                                                </div>
                                                <div class="timeline-comment-box">
                                                    @if (post.Comments.Count > 0)
                                                    {
                                                        @foreach (var comment in post.Comments.OrderByDescending(c => c.CreatedOn))
                                                        {
                                                            <div style="margin-bottom: 3%; padding: 6%; background-color: #fff;">
                                                                <span class="username"><strong>@comment.Author.FullName</strong></span>
                                                                <hr />
                                                                <p>@comment.Content</p>
                                                                <hr />
                                                                <div align="right">
                                                                    <span class="date">@comment.CreatedOn.Date.ToString("dd/MM/yyyy")</span>
                                                                    <span class="time">@comment.CreatedOn.ToString("HH:mm")</span>
                                                                </div>
                                                            </div>
                                                        }
                                                    }
                                                </div>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts{
    <script>
        /* Ajax post request that invoke IncreaseLikes method of posts controller.
         * It pass the post id to the method.
         */
        function increaseLikes(id, userId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("IncreaseLikes", "Posts")',
                data: JSON.stringify({
                        'UserId': userId,
                        'PostId': id,
                    }),
                contentType: 'application/json',
                dataType: 'json',
                success: function (res) {
                    var badgeId = 'users-likes-' + id;
                    //get users-likes badge
                    var badge = document.getElementById(badgeId).innerHTML;
                    //convert users` likes to int
                    var likes = parseInt(badge);

                    if (res === true) {
                        //increase value of users likes badge with one
                        $('#users-likes-' + id).text(likes + 1);
                    }
                    else if (res === false) {
                        //decrease value of users likes badge with one
                        $('#users-likes-' + id).text(likes - 1);
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }
    </script>
}